config/routes.rb
Evosalon::Application.routes.draw do
  devise_for :users
  root :to => 'home#index'
  resources :companies 
  match 'edit_main_company' => 'companies#edit_main_company', :as => :edit_main_company 
  match 'update_company/:id' => 'companies#update_company', :as => :update_company, :method => :post 
  
  resources :users
  resources :app_users
  
  resources :customers 
  resources :services
  resources :employees
  
  
  resources :item_categories do
    resources :items
  end
  resources :items 
  
  resources :items do
    resources :stock_migrations 
  end
  
  resources :service_categories do 
    resources :services 
  end
  resources :services 
  
  resources :stock_migrations
 
=begin
  USER SETTING
=end
  match 'edit_credential' => "passwords#edit_credential" , :as => :edit_credential
  match 'update_password' => "passwords#update" , :as => :update_password, :method => :put
 
##################################################
##################################################
######### APP_USER 
##################################################
##################################################
  match 'update_app_user/:user_id' => 'app_users#update_app_user', :as => :update_app_user , :method => :post 
  match 'delete_app_user' => 'app_users#delete_app_user', :as => :delete_app_user , :method => :post
end

app/models/employee.rb
class Employee < ActiveRecord::Base
  attr_accessible :name, :phone, :mobile , 
                  :email, :bbm_pin, :address 
  
  validates_presence_of :name 
  
  def self.active_objects
    self.where(:is_deleted => false ).order("created_at DESC")
  end
  
  def delete( employee) 
    return nil if employee.nil?
    
    self.is_deleted = true 
    self.save 
  end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_filter :role_required, :except => [:search_employee]
  def new
    @objects = Employee.active_objects
    @new_object = Employee.new 
  end
  
  def create
    # HARD CODE.. just for testing purposes 
    # params[:employee][:town_id] = Town.first.id 
    @object = Employee.create( params[:employee] ) 
    if @object.valid?
      @new_object=  Employee.new
    else
      @new_object= @object
    end
    
  end
  
  def search_employee
    search_params = params[:q]
    
    @objects = [] 
    query = '%' + search_params + '%'
    # on PostGre SQL, it is ignoring lower case or upper case 
    @objects = Employee.where{ (name =~ query)  & (is_deleted.eq false) }.map{|x| {:name => x.name, :id => x.id }}
    
    respond_to do |format|
      format.html # show.html.erb 
      format.json { render :json => @objects }
    end
  end
  
  def edit
    @object = Employee.find_by_id params[:id] 
  end
  
  def update
    @object = Employee.find_by_id params[:id] 
    
    @object.update_attributes( params[:employee])
    @has_no_errors  = @object.errors.messages.length == 0
  end
  
  def destroy
    @object = Employee.find_by_id params[:id]
    @object.delete(current_user )
  end
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_entry.html.erb
 
<tr id="entry-<%= object.id %>">
	<td>
		<%= "#{object.name}" %>
	</td>
	<td>
		<ul>
			<li>Telpon: <%= object.phone %></li>
			<li>HP: <%= object.mobile %></li>
			<li>BBM Pin: <%= object.bbm_pin %></li>
			<li>Email: <%= object.email %></li>
		</ul> 
	</td>



	<td>
		 <%= object.address %>
	</td>

	<td>
		<%= link_to employee_url(object.id ), :class =>"delete_entry", :style => "cursor:pointer; text-decoration:none;" do %>
			<i class='icon-remove'></i>Delete
		<% end %> 
	</td>

	<td>
		<%= link_to edit_employee_url(object.id), 
			:class =>"edit_entry modal-toggler", :style => "cursor:pointer; text-decoration:none;" do %>
			<i class='icon-edit'></i>Edit
		<% end %>
	</td>

</tr> 

app/views/employees/_new_object_form.html.erb
<% if new_object.persisted? %>
	<% id = 'edit_object'%>
	<% rest_method_class = 'rest_put' %>
<% else %>
	<% id = 'new_object'%>
	<% rest_method_class = 'rest_post' %>
<% end %>

<%= simple_form_for( new_object, :url => url,
      :method => :post , 
      :html => {:class => "form-horizontal prevent_double_submit ajax-form #{rest_method_class}  no_content_form",
        :id => "#{id}"}) do |f| %>

	 


  <%= f.input :name  , :input_html => {:class => "input-xlarge "}, 
  :label => "Name" %>
 
<hr />
	<%= f.input :phone  , :input_html => {:class => "input-xlarge "}, 
  :label => "Telepon" %>

	<%= f.input :mobile  , :input_html => {:class => "input-xlarge "}, 
  :label => "HP" %>

	<%= f.input :bbm_pin  , :input_html => {:class => "input-xlarge "}, 
  :label => "BBM" %>


	<%= f.input :email  , :input_html => {:class => "input-xlarge "}, 
  :label => "Email" %>
 
<hr />

	<%= f.input :address  , :input_html => {:class => "input-xlarge ", :rows => 3}, 
  :label => "Alamat " %>


  <div class="form-actions">
	
		<% if new_object.persisted? %>
			<%= f.button :submit , :class => "btn btn-primary", :value=> "Update Employee" %>
		<% else %>
			<%= f.button :submit , :class => "btn btn-primary", :value=> "Create Employee" %>
		<% end %>
		
  </div>
<% end %>

app/views/employees/create.js.erb
$(document).ready(function(){
	 
	var $modal = $("#newEntry"); 
	var $form = $("form", $modal );
	$form.spin(false);
	
	<% new_form = escape_javascript(  render :partial => "employees/new_object_form", :locals => {
    :new_object => @new_object , 
		:url => employees_url,
  })%>

 
	
	<% if @object.valid? %>
		// show the growl. save. done. 
		<% new_entry = escape_javascript(  render :partial => "employees/entry", :locals => {
	    :object => @object  
	  })%>
		$("#tableview tbody").prepend('<%= new_entry %>');
		
		$.msgbox("Employee <b><%= @object.name %></b> is created.", 
					{type: "info"});
		$modal.modal('hide'); 
		$form.remove();
	<% else %>
		$form.replaceWith('<%= new_form %>');
		 $.msgbox("Gagal membuat Employee baru.", 
					{type: "error"});
	<% end %>
	
	
	// else, display error.. 
	jQuery('.prevent_double_submit').preventDoubleSubmit();
});

app/views/employees/edit.js.erb
$(document).ready(function(){
	  
		<% new_form = escape_javascript(  render :partial => "employees/new_object_form", :locals => {
	    :new_object => @object , 
			:url => employee_url(@object)  
	  })%>
 
	$("#editEntry .modal-body").append('<%= new_form %>');
	
	jQuery('.prevent_double_submit').preventDoubleSubmit();
});

app/views/employees/new.html.erb
<%= render :partial => "layouts/masthead" ,:locals => {
	:title => "Karyawan",
	:description => "Tambah informasi karyawan ke database"
}%>

<div id="content">

	<div class="container">
		
		
		<div class="row">
			
			<div class="span8">
				
				<%= link_to new_employee_url, :class => "new_entry btn btn-primary" do %>
					<i class="icon-plus"></i>Employee Baru
				<% end %> 
				<hr />
			

				<table class="table table-bordered table-striped table-highlight" id='tableview'>
					<thead>
						<tr>
							<th>Name</th>
							<th>Kontak</th> 
							<th>Alamat</th>
							<th colspan='2'>Action</th>
						</tr>
					</thead>
					<tbody> 
						<% @objects.each do |object| %>
							<%= render :partial =>  'employees/entry', :locals => {
								:object => object 
							} %> 
						<% end %>
					</tbody>
				</table>

				
				
				
			 
				
			</div> <!-- /.span8 -->
			
			
			<div class="span4">
				
						
				<a href="javascript:;" class="btn btn-large btn-primary btn-block btn-big-block">Tree View</a>	
				
				
				<a href="javascript:;" class="btn btn-large btn-tertiary btn-block btn-big-block">Contact Support</a>
				
				
				<div>
				</div> <!-- /.table wrapper -->
						
				
			</div> <!-- /.span4 -->
			
		</div> <!-- /.row -->
		
	
	</div> <!-- /.container -->

</div> <!-- /#content -->


<div class="modal fade hide" id="editEntry">
  <div class="modal-header">
    <h3>Edit Employee</h3>
  </div>
  <div class="modal-body"> 
	<!-- content -->
  </div>
  <div class="modal-footer">
    <!-- <a href="javascript:;" class="btn" data-dismiss="modal">Close</a> -->
		<a  class="btn modal_closer"  >Close</a>
  </div>
</div>

<div class="modal fade hide" id="newEntry">
  <div class="modal-header">
    <h3>New Employee</h3>
  </div>
  <div class="modal-body"> 
	<!-- content -->
  </div>
  <div class="modal-footer">
    <!-- <a href="javascript:;" class="btn" data-dismiss="modal">Close</a> -->
		<a  class="btn modal_closer"  >Close</a>
  </div>
</div>


<div class="hidden" id="delete_entry_form_wrapper">
  <%= form_for Employee.new, :url => root_url  , :method => :post   do |f| %>
    <%= hidden_field_tag 'object_to_destroy_id' , ''  %> 
  <% end %>
</div>


<% content_for :additional_js do %> 
	<%= javascript_include_tag "common_order/entry_creation"  	%>
<% end %>

app/views/employees/new.js.erb
$(document).ready(function(){
	  
		<% new_form = escape_javascript(  render :partial => "employees/new_object_form", :locals => {
	    :new_object => @new_object , 
			:url => employees_url 
	  })%>
 
	$("#newEntry .modal-body").append('<%= new_form %>');
	
	jQuery('.prevent_double_submit').preventDoubleSubmit();
});

app/views/employees/update.js.erb
$(document).ready(function(){
	// remove the spin
	
	var $modal = $("#editEntry");
	var $form = $("form", $modal );
	$form.spin(false); 
	
	// if update is successful
		// remove the form 
		// hide the modal 
		// update the row entry 
	// else
		// replace the form with the faulty one 
		// show all the error 
	
	
		<% if   @has_no_errors  %> 
			// clean the add product form
			$form.remove(); 

			<% new_entry  = escape_javascript( render :partial =>  'employees/entry', :locals => {
				:object => @object 
			} )%>

			$("#entry-<%= @object.id %>").replaceWith('<%= new_entry %>') 

			$.msgbox("Berhasil update Employee: <%= @object.name %>", 
						{type: "info"});

			
			$modal.modal('hide'); 


		<% elsif  not @has_no_errors %> 
			<% new_form = escape_javascript(   render :partial => "employees/new_object_form", :locals => {
		    :new_object => @object , 
				:url => update_employee_url(@object)  
		  })%>
			//replace the form, show the edit
			$form.replaceWith("<%= new_form %>"); 

			$.msgbox("Error dalam update employee: <%= @object.name %>", 
						{type: "error"});
		<% end %>



		jQuery('.prevent_double_submit').preventDoubleSubmit(); 
});