config/routes.rb
Evosalon::Application.routes.draw do
  devise_for :users
  root :to => 'home#index'
  resources :companies 
  match 'edit_main_company' => 'companies#edit_main_company', :as => :edit_main_company 
  match 'update_company/:id' => 'companies#update_company', :as => :update_company, :method => :post 
  
  resources :users
  resources :app_users
  
  resources :customers 
  resources :services
  resources :employees
  
  
  resources :item_categories do
    resources :items
  end
  resources :items 
  
  resources :items do
    resources :stock_migrations 
  end
  
  resources :service_categories do 
    resources :services 
  end
  resources :services 
  
  resources :stock_migrations
 
=begin
  USER SETTING
=end
  match 'edit_credential' => "passwords#edit_credential" , :as => :edit_credential
  match 'update_password' => "passwords#update" , :as => :update_password, :method => :put
 
##################################################
##################################################
######### APP_USER 
##################################################
##################################################
  match 'update_app_user/:user_id' => 'app_users#update_app_user', :as => :update_app_user , :method => :post 
  match 'delete_app_user' => 'app_users#delete_app_user', :as => :delete_app_user , :method => :post
end

app/models/service_category.rb
class ServiceCategory < ActiveRecord::Base 
  has_many :services
  attr_accessible :name, :parent_id
  acts_as_nested_set
  
  validates_presence_of :name
  # validates_uniqueness_of :name,   :case_sensitive => false , :if => :no_other_active_entry #, :scope => { }
  # validate :uniqueness_of_name_if_not_deleted
  validate :unique_non_deleted_name  , :parent_can_not_be_self
  
  def unique_non_deleted_name
    current_object = self
     
     # claim.status_changed?
    if not current_object.name.nil? 
      if not current_object.persisted? and current_object.has_duplicate_entry?  
        errors.add(:name , "Sudah ada service category  dengan nama sejenis" )  
      elsif current_object.persisted? and 
            current_object.name_changed?  and
            current_object.has_duplicate_entry?   
            # if duplicate entry is itself.. no error
            # else.. some error
            
          if current_object.duplicate_entries.count ==1  and 
              current_object.duplicate_entries.first.id == current_object.id 
          else
            errors.add(:name , "Sudah ada service category dengan nama sejenis" )  
          end 
      end
    end
  end
  
  def parent_can_not_be_self
    current_object = self
    if current_object.persisted? and current_object.id == current_object.parent_id 
      errors.add(:parent_id , "Tidak boleh sama dengan object sekarang" )  
    end
  end
  
  def has_duplicate_entry?
    current_object  =  self  
    self.class.find(:all, :conditions => ['lower(name) = :name and is_deleted = :is_deleted  ', 
                {:name => current_object.name.downcase, :is_deleted => false }]).count != 0  
  end
  
  def duplicate_entries
    current_object  =  self  
    return self.class.find(:all, :conditions => ['lower(name) = :name and is_deleted = :is_deleted   ', 
                {:name => current_object.name.downcase, :is_deleted => false  }]) 
  end
  
  def self.create_by_employee(employee,  object_params ) 
    return nil if employee.nil? 
     
    new_object = self.new  
    new_object.creator_id = employee.id 
    new_object.name = object_params[:name]
    new_object.parent_id =  object_params[:parent_id]
    new_object.save 
     
    return new_object
  end
  
  def update_by_employee( employee, object_params )
    return nil if employee.nil? 
    
    self.creator_id = employee.id
    
    self.name = object_params[:name]
    self.parent_id = object_params[:parent_id]
    
    self.save
    return self 
  end
   
  
  def self.active_objects
    self.where(:is_deleted => false).order("created_at DESC")
  end
  
  
  def self.create_base_object( employee, object_params ) 
    return nil if employee.nil? 
    
    new_object = self.new 
    new_object.creator_id = employee.id 
    new_object.is_base_category = true 
    new_object.name = object_params[:name]
    
    new_object.save
    return new_object 
  end
   
  
  def active_services
    self.services.where(:is_deleted => false).order("created_at DESC")
  end
  
  def self.all_selectable_objects
    objects  = self.where(:is_deleted => false ).order("depth  ASC ")
    result = []
    objects.each do |object| 
      result << [ "#{object.name}" , 
                      object.id ]  
    end
    return result
  end
  
  def delete(employee)
    parent = self.parent 
    if parent.nil?
      # can't be deleted from the base
      return nil
    end
   
    ActiveRecord::Base.transaction do
      self.is_deleted = true
      self.save

      self.class.where(:parent_id => self.id ).each do |sub_category|
        sub_category.parent_id = self.parent_id 
        sub_category.save 
      end
    end
    
    
    # self.services.each do |service|
    #   service.service_category_id = parent.id
    #   service.save 
    # end
    # what will happen to the item from this category? Go to the parent category 
  end
end

app/controllers/service_categories_controller.rb
class ServiceCategoriesController < ApplicationController
  def new
    @objects = ServiceCategory.active_objects 
    @new_service_category = ServiceCategory.new 
    @new_object = @new_service_category
    
    respond_to do |format|
      format.html # show.html.erb 
      format.js 
    end
  end
  
  def create
    base_service_category = ServiceCategory.find_by_id params[:service_category][:parent_id]
    
    # sleep 5
    
    @object = base_service_category.create_sub_object( params[:service_category] ) 
    if @object.valid?
      @new_object=  ServiceCategory.new
    else
      @new_object= @object
    end
    
  end
  
  def edit
    @object = ServiceCategory.find_by_id params[:id] 
  end
  
  def update 
    @object = ServiceCategory.find_by_id params[:id] 
    @object.update_attributes( params[:service_category])
    @has_no_errors  = @object.errors.messages.length == 0
  end
  
  def destroy
    @object = ServiceCategory.find_by_id params[:id]
    @object.delete(current_user )
  end
  
end

app/helpers/service_categories_helper.rb
module ServiceCategoriesHelper
end

app/views/service_categories/_entry.html.erb
 
<tr id="entry-<%= object.id %>">
	<td>
		<%= "#{object.name}" %>
	</td> 
	
 

	<td>
		 <%= object.active_services.count %>
	</td>
	
	<td>
		<%= link_to service_category_url(object.id ), :class =>"delete_entry", :style => "cursor:pointer; text-decoration:none;" do %>
			<i class='icon-remove'></i>Delete
		<% end %> 
	</td>

	<td>
		<%= link_to edit_service_category_url(object.id), 
			:class =>"edit_entry modal-toggler", :style => "cursor:pointer; text-decoration:none;" do %>
			<i class='icon-edit'></i>Edit
		<% end %>
	</td>
	
</tr>

app/views/service_categories/_new_object_form.html.erb
<% if new_object.persisted? %>
	<% id = 'edit_object'%>
	<% rest_method_class = 'rest_put' %>
<% else %>
	<% id = 'new_object'%>
	<% rest_method_class = 'rest_post' %>
<% end %>

<%= simple_form_for( new_object, :url => url,
      :method => :post , 
      :html => {:class => "form-horizontal prevent_double_submit ajax-form  #{rest_method_class} no_content_form",
        :id => "#{id}"}) do |f| %>

	<%#= f.input :parent_id , :label => "Super Category" %>
	
	<%= f.input :parent_id, :hint => "Parent Category", :label => "Parent Category" do %>
     <%= f.select :parent_id, 
         ServiceCategory.all_selectable_objects %>
   <% end %>

  <%= f.input :name  , :input_html => {:class => "input-xlarge "}, 
  :label => "Name" %>


  <div class="form-actions">
		<% if new_object.persisted? %>
			<%= f.button :submit , :class => "btn btn-primary", :value=> "Update Service Category" %>
		<% else %>
			<%= f.button :submit , :class => "btn btn-primary", :value=> "Create Service Category " %>
		<% end %> 
  </div>
<% end %>

app/views/service_categories/create.js.erb
$(document).ready(function(){
	 
	var $modal = $("#newEntry"); 
	var $form = $("form", $modal );
	$form.spin(false);
	
	<% new_form = escape_javascript(  render :partial => "service_categories/new_object_form", :locals => {
    :new_object => @new_object , 
		:url => service_categories_url,
  })%>

 
	
	<% if @object.valid? %>
		// show the growl. save. done. 
		<% new_entry = escape_javascript(  render :partial => "service_categories/entry", :locals => {
	    :object => @object  
	  })%>
		$("#tableview tbody").prepend('<%= new_entry %>');
		
		$.msgbox("Item Service Category <b><%= @object.name %></b> is created.", 
					{type: "info"});
		$modal.modal('hide'); 
		$form.remove();
	<% else %>
		$form.replaceWith('<%= new_form %>');
		 $.msgbox("Gagal membuat  Service Category baru.", 
					{type: "error"});
	<% end %>
	
	
	// else, display error.. 
	jQuery('.prevent_double_submit').preventDoubleSubmit();
});

app/views/service_categories/edit.js.erb
$(document).ready(function(){
	  
		<% new_form = escape_javascript(  render :partial => "service_categories/new_object_form", :locals => {
	    :new_object => @object , 
			:url => service_category_url(@object)  
	  })%>
 
	$("#editEntry .modal-body").append('<%= new_form %>');
	
	jQuery('.prevent_double_submit').preventDoubleSubmit();
});

app/views/service_categories/new.html.erb
<%= render :partial => "layouts/masthead" ,:locals => {
	:title => "Kategori Item",
	:description => "Tambah informasi kategori item ke database"
}%>

<div id="content">

	<div class="container">
		
		
		<div class="row">
			
			<div class="span8">
				
				<%= link_to new_service_category_url, :class => "new_entry btn btn-primary" do %>
					<i class="icon-plus"></i>Service Category Baru
				<% end %> 
				<hr />
			

				<table class="table table-bordered table-striped table-highlight" id='tableview'>
					<thead>
						<tr>
							<th>Name</th>
							<th>Total Service</th>  
							<th colspan='2'>Action</th>
						</tr>
					</thead>
					<tbody> 
						<% @objects.each do |object| %>
							<%= render :partial =>  'service_categories/entry', :locals => {
								:object => object 
							} %> 
						<% end %>
					</tbody>
				</table>

				
				
				
			 
				
			</div> <!-- /.span8 -->
			
			
			<div class="span4">
				
						
				<a href="javascript:;" class="btn btn-large btn-primary btn-block btn-big-block">Tree View</a>	
				
				
				<a href="javascript:;" class="btn btn-large btn-tertiary btn-block btn-big-block">Contact Support</a>
				
				
				<div>
				</div> <!-- /.table wrapper -->
						
				
			</div> <!-- /.span4 -->
			
		</div> <!-- /.row -->
		
	
	</div> <!-- /.container -->

</div> <!-- /#content -->


<div class="modal fade hide" id="editEntry">
  <div class="modal-header">
    <h3>Edit Service Category</h3>
  </div>
  <div class="modal-body"> 
	<!-- content -->
  </div>
  <div class="modal-footer">
    <!-- <a href="javascript:;" class="btn" data-dismiss="modal">Close</a> -->
		<a  class="btn modal_closer"  >Close</a>
  </div>
</div>

<div class="modal fade hide" id="newEntry">
  <div class="modal-header">
    <h3>New Service Category</h3>
  </div>
  <div class="modal-body"> 
	<!-- content -->
  </div>
  <div class="modal-footer">
    <!-- <a href="javascript:;" class="btn" data-dismiss="modal">Close</a> -->
		<a  class="btn modal_closer"  >Close</a>
  </div>
</div>


<div class="hidden" id="delete_entry_form_wrapper">
  <%= form_for Employee.new, :url => root_url  , :method => :post   do |f| %>
    <%= hidden_field_tag 'object_to_destroy_id' , ''  %> 
  <% end %>
</div>


<% content_for :additional_js do %> 
	<%= javascript_include_tag "common_order/entry_creation"  	%>
<% end %>

app/views/service_categories/new.js.erb
$(document).ready(function(){
	  
		<% new_form = escape_javascript(  render :partial => "service_categories/new_object_form", :locals => {
	    :new_object => @new_object , 
			:url => service_categories_url 
	  })%>
 
	$("#newEntry .modal-body").append('<%= new_form %>');
	
	jQuery('.prevent_double_submit').preventDoubleSubmit();
});

app/views/service_categories/update.js.erb
$(document).ready(function(){
	// remove the spin
	
	var $modal = $("#editEntry");
	var $form = $("form", $modal );
	$form.spin(false); 
	
	// if update is successful
		// remove the form 
		// hide the modal 
		// update the row entry 
	// else
		// replace the form with the faulty one 
		// show all the error 
	
	
		<% if   @has_no_errors  %> 
			// clean the add product form
			$form.remove(); 

			<% new_entry  = escape_javascript( render :partial =>  'service_categories/entry', :locals => {
				:object => @object 
			} )%>

			$("#entry-<%= @object.id %>").replaceWith('<%= new_entry %>') 

			$.msgbox("Berhasil update service category: <%= @object.name %>", 
						{type: "info"});

			
			$modal.modal('hide'); 


		<% elsif  not @has_no_errors %> 
			<% new_form = escape_javascript(   render :partial => "service_categories/new_object_form", :locals => {
		    :new_object => @object , 
				:url => service_category_url(@object)  
		  })%>
			//replace the form, show the edit
			$form.replaceWith("<%= new_form %>"); 

			$.msgbox("Error dalam update service_category: <%= @object.name %>", 
						{type: "error"});
		<% end %>



		jQuery('.prevent_double_submit').preventDoubleSubmit(); 
});