config/routes.rb
Evosalon::Application.routes.draw do
  devise_for :users
  root :to => 'home#index'
  resources :companies 
  match 'edit_main_company' => 'companies#edit_main_company', :as => :edit_main_company 
  match 'update_company/:id' => 'companies#update_company', :as => :update_company, :method => :post 
  
  resources :users
  resources :app_users
  
  resources :customers 
  resources :services
  resources :employees
  
  
  resources :item_categories do
    resources :items
  end
  resources :items 
  
  resources :items do
    resources :stock_migrations 
  end
  
  resources :service_categories do 
    resources :services 
  end
  resources :services 
  
  resources :stock_migrations
 
=begin
  USER SETTING
=end
  match 'edit_credential' => "passwords#edit_credential" , :as => :edit_credential
  match 'update_password' => "passwords#update" , :as => :update_password, :method => :put
 
##################################################
##################################################
######### APP_USER 
##################################################
##################################################
  match 'update_app_user/:user_id' => 'app_users#update_app_user', :as => :update_app_user , :method => :post 
  match 'delete_app_user' => 'app_users#delete_app_user', :as => :delete_app_user , :method => :post
end

app/controllers/app_users_controller.rb
class AppUsersController < ApplicationController
  before_filter :role_required
  
  def new
    @objects = User.active_objects
    @new_object = User.new 
  end
  
  def create
    # HARD CODE.. just for testing purposes 
    # params[:customer][:town_id] = Town.first.id 
    @object = User.create_by_employee(current_user,  params[:user] ) 
    if @object.valid?
      @new_object=  User.new
    else
      @new_object= @object
    end
  end
  
  def edit
    @object = User.find_by_id params[:id] 
  end
  
  def update_app_user
    @object = User.find_by_id params[:user_id] 
    @object.update_by_employee(current_user,  params[:user])
    @has_no_errors  = @object.errors.messages.length == 0
  end
  
  def delete_app_user
    @object = User.find_by_id params[:object_to_destroy_id]
    @object_identifier = @object.name 
    @object.delete(current_user)
  end
end

app/helpers/app_users_helper.rb
module AppUsersHelper
end

app/views/app_users/_entry.html.erb
 
<tr id="entry-<%= object.id %>"> 
	<td>
		<%= "#{object.name}" %>
	</td>
	
	<td>
		<%= "#{object.email}" %>
	</td>
	
	<td>
		<%= "#{object.role.name }" %>
	</td>
	 
	
	<td>
		<%= link_to root_url, :class =>"delete_entry", :style => "cursor:pointer; text-decoration:none;" do %>
			<i class='icon-remove'></i>Delete
		<% end %> 
	</td>

	<td>
		<%= link_to edit_app_user_url(object), 
			:class =>"edit_entry modal-toggler", :style => "cursor:pointer; text-decoration:none;" do %>
			<i class='icon-edit'></i>Edit
		<% end %>
	</td>
	
</tr>

app/views/app_users/_new_object_form.html.erb
<% if new_object.persisted? %>
	<% id = 'edit_object'%>
<% else %>
	<% id = 'new_object'%>
<% end %>

<%= simple_form_for( new_object, :url => url,
      :method => :post , 
      :html => {:class => " prevent_double_submit ajax-form   no_content_form",
        :id => "#{id}"}) do |f| %>

	 
 

  <%= f.input :name  , :input_html => {:class => "input-xlarge "}, 
  			:label => "Name" %>
 
	<%= f.input :email  , :input_html => {:class => "input-xlarge "}, 
  			:label => "Email" %>

 

<hr />

	<% if not  new_object.is_main_user? %>
		<%= f.input :role_id, :label => "Role" do %>
	     <%= f.select :role_id, 
	         Role.all_selectables %>
	  <% end %>
	<% end %>

  <div class="form-actions">
	
		<% if new_object.persisted? %>
			<%= f.button :submit , :class => "btn btn-primary", :value=> "Update  User" %>
		<% else %>
			<%= f.button :submit , :class => "btn btn-primary", :value=> "Create User" %>
		<% end %>
		
  </div>
<% end %>


 

app/views/app_users/create.js.erb
$(document).ready(function(){
	 
	var $modal = $("#newEntry"); 
	var $form = $("form", $modal );
	$form.spin(false);
	
	<% new_form = escape_javascript(  render :partial => "app_users/new_object_form", :locals => {
    :new_object => @new_object , 
		:url => app_users_url,
  })%>

 
	
	<% if @object.errors.size == 0  %>
		// show the growl. save. done. 
		<% new_entry = escape_javascript(  render :partial => "app_users/entry", :locals => {
	    :object => @object  
	  })%>
		$("#tableview tbody").prepend('<%= new_entry %>');
		
		$.msgbox("User <b><%= @object.name %></b> is created.", 
					{type: "info"});
		$modal.modal('hide'); 
		$form.remove();
	<% else %>
		$form.replaceWith('<%= new_form %>');
		 $.msgbox("Gagal membuat User baru.", 
					{type: "error"});
	<% end %>
	
	
	// else, display error.. 
	jQuery('.prevent_double_submit').preventDoubleSubmit();
});

app/views/app_users/delete_app_user.js.erb
$(document).ready(function(){
	
	var $row = $("#entry-<%= @object.id %>")
	$row.spin(false); 
	
	$row.remove(); 
	
	$.msgbox("Berhasil menghapus user: <%= @object_identifier %>");
	 
	
});

app/views/app_users/edit.js.erb
$(document).ready(function(){
	  
		<% new_form = escape_javascript(  render :partial => "app_users/new_object_form", :locals => {
	    :new_object => @object , 
			:url => update_app_user_url(@object)  
	  })%>
 
	$("#editEntry .modal-body").append('<%= new_form %>');
	
	jQuery('.prevent_double_submit').preventDoubleSubmit();
});

app/views/app_users/new.html.erb
<%= render :partial => "layouts/masthead" ,:locals => {
	:title => "User Management",
	:description => "Buat / Edit user baru"
}%>

<div id="content">

	<div class="container">
		
		
		<div class="row">
			
			<div class="span8">
				
				<%= link_to new_app_user_url, :class => "new_entry btn btn-primary" do %>
					<i class="icon-plus"></i>User
				<% end %> 
				<hr />
				 
				
				<%#= render :partial => "customers/new_object_form", :locals => {
					:new_object => @new_object , 
					:url => customers_url
				}%>


				<table class="table table-bordered table-striped table-highlight" id='tableview'>
					<thead>
						<tr>
							<th>Name</th> 
							<th>Email</th>
							<th>Role</th>
							
							<th colspan='2'>Action</th>
						</tr>
					</thead>
					<tbody> 
						<% @objects.each do |object| %>
							<%= render :partial =>  'app_users/entry', :locals => {
								:object => object 
							} %> 
						<% end %>
					</tbody>
				</table>

				
				
				
			 
				
			</div> <!-- /.span8 -->
			
			
			<div class="span4">
				
						
				<a href="javascript:;" class="btn btn-large btn-primary btn-block btn-big-block">Tree View</a>	
				
				
				<a href="javascript:;" class="btn btn-large btn-tertiary btn-block btn-big-block">Contact Support</a>
				
				
				<div>
				</div> <!-- /.table wrapper -->
						
				
			</div> <!-- /.span4 -->
			
		</div> <!-- /.row -->
		
	
	</div> <!-- /.container -->

</div> <!-- /#content -->


<div class="modal fade hide" id="editEntry">
  <div class="modal-header">
    <h3>Edit User</h3>
  </div>
  <div class="modal-body"> 
	<!-- content -->
  </div>
  <div class="modal-footer">
    <!-- <a href="javascript:;" class="btn" data-dismiss="modal">Close</a> -->
		<a  class="btn modal_closer"  >Close</a>
  </div>
</div>

<div class="modal fade hide" id="newEntry">
  <div class="modal-header">
    <h3>New User</h3>
  </div>
  <div class="modal-body"> 
	<!-- content -->
  </div>
  <div class="modal-footer">
    <!-- <a href="javascript:;" class="btn" data-dismiss="modal">Close</a> -->
		<a  class="btn modal_closer"  >Close</a>
  </div>
</div>


<div class="hidden" id="delete_entry_form_wrapper">
  <%= form_for User.new, :url =>delete_app_user_url , :method => :post   do |f| %>
    <%= hidden_field_tag 'object_to_destroy_id' , ''  %> 
  <% end %>
</div>


<%# content_for :additional_js do %> 
	<%#= javascript_include_tag "common_order/entry_creation"  	%>
<%# end %>

<% content_for :additional_js do %> 
  <%= javascript_include_tag "common_order/entry_creation" %> 
 
<% end %>
 

app/views/app_users/new.js.erb
$(document).ready(function(){
	  
		<% new_form = escape_javascript(  render :partial => "app_users/new_object_form", :locals => {
	    :new_object => @new_object , 
			:url => app_users_url 
	  })%>
 
	$("#newEntry .modal-body").append('<%= new_form %>');
	
	jQuery('.prevent_double_submit').preventDoubleSubmit();
});

app/views/app_users/update_app_user.js.erb
$(document).ready(function(){
	// remove the spin
	
	var $modal = $("#editEntry");
	var $form = $("form", $modal );
	$form.spin(false); 
	
	// if update is successful
		// remove the form 
		// hide the modal 
		// update the row entry 
	// else
		// replace the form with the faulty one 
		// show all the error 
	
	
		<% if   @has_no_errors  %> 
			// clean the add product form
			$form.remove(); 

			<% new_entry  = escape_javascript( render :partial =>  'app_users/entry', :locals => {
				:object => @object 
			} )%>

			$("#entry-<%= @object.id %>").replaceWith('<%= new_entry %>') 

			$.msgbox("Berhasil update user: <%= @object.name %>", 
						{type: "info"});

			
			$modal.modal('hide'); 


		<% elsif  not @has_no_errors %> 
			<% new_form = escape_javascript(   render :partial => "app_users/new_object_form", :locals => {
		    :new_object => @object , 
				:url => update_app_user_url(@object)  
		  })%>
			//replace the form, show the edit
			$form.replaceWith("<%= new_form %>"); 

			$.msgbox("Error dalam update user : <%= @object.name %>", 
						{type: "error"});
		<% end %>



		jQuery('.prevent_double_submit').preventDoubleSubmit(); 
});